### ISSUE TITLE
Proguard causes crash on startup

### ISSUE THREAD

**Issue by corymsmith** [davodesign84/react-native-mixpanel#96]
With Proguard on it crashes, with Proguard disabled it works, I added the proguard settings that Mixpanel recommends so I'm not quite sure whats going on. Any ideas?

```
09:30.831 15238-15279/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.mpmetrics.MixpanelAPI.track(java.lang.String, org.json.JSONObject)' on a null object reference
                                                       at com.kevinejohn.RNMixpanel.RNMixpanelModule.trackWithProperties(RNMixpanelModule.java:122)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:168)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                       at java.lang.Thread.run(Thread.java:818)
```

**Comment by anubhav193** [comment]
Any update on this?

**Comment by ptmt** [comment]
I had the same issue because I called `track` before `sharedInstanceWithToken`. Basically that errors means that you have not initialized your `mixpanel` object. Make sure it comes first.

**Comment by akshay2604** [comment]
How did you solve it? what are the steps.

**Comment by ptmt** [comment]
I  changed the order of execution. Of course, it could be in different files, so you need to make sure it's chronologically correct:
```js
const Mixpanel = require('react-native-mixpanel');

// make sure Config.MIXPANEL_TOKEN) is not null and have an actual value
Mixpanel.sharedInstanceWithToken(Config.MIXPANEL_TOKEN);
...
// somewhere later
Mixpanel.registerSuperProperties({
      ...
}), 
```

**Comment by imtmh** [comment]
For me, the issue was because of the Config, Config.MIXPANEL_TOKEN was null. make sure it is not null.
